import './globals.css'
import './../quantum/assets/release/qn-202307280002.css'

import type { Metadata } from 'next'
import { Navbar } from '@/components/navbar/Navbar'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Sevima University',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='body_white'>
        {children}
        <Script
          src='/quantum/assets/release/qn-202307280002.js'
        />
      </body>
    </html>
  )
}
